//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int id { get; set; }
        public int Hiren_Employeeid { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Marks { get; set; }
        public string Exam_date { get; set; }
    
        public virtual Hiren_Employee Hiren_Employee { get; set; }
    }
}
